import type { Metadata } from "next";
import { Almarai } from "next/font/google";
import "../globals.css";
import { getMessages } from "next-intl/server";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import { ThemeProvider } from "@/providers/theme-provider";
import { AuthProvider } from "@/providers/auth-provider";
import { Toaster } from "@/components/ui/sonner";
import Navbar from "./componenets/navbar";
import { headers } from "next/headers";
import Footer from "./componenets/footer";
import AnimationContainer from "@/components/animation-container";


// Load only the Almarai font
const almarai = Almarai({
  subsets: ["arabic", "latin"], // include both if you support Arabic
  weight: ["400", "700"], // adjust weights as needed (400 = regular, 700 = bold)
  variable: "--font-almarai",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string }
}>) {

  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  const messages = await getMessages();


  return (
    <html lang={locale} dir={locale == "ar" ? "rtl" : "ltr"} suppressHydrationWarning>
      <body
        className={`${almarai.variable} font-sans  antialiased `}
        suppressHydrationWarning
      >
        <ThemeProvider>

          <NextIntlClientProvider messages={messages} locale={locale}>

           
            <AuthProvider>
               <Navbar />
              <Toaster />
              {children}
            </AuthProvider>

       
              <Footer />
    

          </NextIntlClientProvider>
        </ThemeProvider>
      </body>
    </html >
  );
}
